Add new macros for sqlserver
dbt-msft/tsql-utils pull request #11
Opened 2020-12-17 08:34 UTC by jkock

2020-12-17 22:57 UTC, alittlesliceoftom reviewed
@swanderz  any idea why the CI hasn't run on this PR?

2020-12-18 00:16 UTC, swanderz commented
> @swanderz any idea why the CI hasn't run on this PR?

there's a setting you have to click for each repo to allow builds to be run on forks. changed it and we're good to go now!

2020-12-18 00:17 UTC, swanderz commented on macros/dbt_utils/cross_db_utils/hash.sql
> +    CONVERT(VARCHAR(32), HASHBYTES('MD5',  COALESCE(CAST({{field}} AS VARCHAR(MAX) ), '')), 2)
i'm sure there's a reason, and I'd love to know why!

2020-12-19 19:44 UTC, alittlesliceoftom requested changes
Hey @jkock this is excellent, thanks so much for the PR, a big improvement. 

The CI is now running on your PR by some magic, there are 7 tests still failing, but if we can resolve the below comments we can merge as master would fail 15 tests right now (pre-release).

There are 2 issues. 
1 date_trunc is wrong and failing tests (please see my comments and either delete or fix)
2 the hash function has some new complexity so would just love to understand the reasoning before merging.

2020-12-19 19:44 UTC, alittlesliceoftom commented on macros/dbt_utils/cross_db_utils/split_part.sql
> +    LTRIM(CAST(('<X>'+REPLACE({{ string_text }},{{ delimiter_text }} ,'</X><X>')+'</X>') AS XML).value('(/X)[{{ part_number }}]', 'VARCHAR(128)'))
I don't understand this logic so a comment would be lovely, but it passes the Azure SQL tests at least.

2020-12-19 19:44 UTC, alittlesliceoftom commented on macros/dbt_utils/cross_db_utils/date_trunc.sql
> +{% macro sqlserver__date_trunc(datepart, date) %}
Fails test with:

  ('22018', '[22018] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Explicit conversion from data type int to date is not allowed. (529) (SQLExecDirectW)')


Though that implies the incoming data is not a date possibly?

2020-12-19 19:44 UTC, alittlesliceoftom commented on macros/dbt_utils/cross_db_utils/date_trunc.sql
> +{% macro sqlserver__date_trunc(datepart, date) %}
Ah, so verifying this - the test is that the value is the rounded day. 

select
    cast({{dbt_utils.date_trunc('day', 'updated_at') }} as date) as actual,
    day as expected

from data

the logic here is actually taking the day of the month,  that is in SQL: 
SELECT     datepart(day, '2015-01-01 12:00') 
, returns 1 hence the error. 

The function should return the day if 'day' is supplied, or the first of the month if 'month' is supplied according to the tests. 

Seems like we  could ref last_day.sql, and simply add 1 day and subtract 1 month or many other ways of doing the same.

2020-12-22 09:31 UTC, jkock commented on macros/dbt_utils/cross_db_utils/hash.sql
> +    CONVERT(VARCHAR(32), HASHBYTES('MD5',  COALESCE(CAST({{field}} AS VARCHAR(MAX) ), '')), 2)
Good question. I was trying to get the surrogate_key() macro working, and someone suggested this fix for the hash macro. But I also did something on another macro, which probably fixed it. Will revert these changes

2020-12-22 09:46 UTC, jkock commented on macros/dbt_utils/cross_db_utils/split_part.sql
> +    LTRIM(CAST(('<X>'+REPLACE({{ string_text }},{{ delimiter_text }} ,'</X><X>')+'</X>') AS XML).value('(/X)[{{ part_number }}]', 'VARCHAR(128)'))
Added a link to some more information

2020-12-22 10:22 UTC, jkock commented on macros/dbt_utils/cross_db_utils/date_trunc.sql
> +{% macro sqlserver__date_trunc(datepart, date) %}
I've changed the behavior

2020-12-22 22:37 UTC, swanderz commented
my feeling is to merge these changes in, and slowly chip away at the remaining errors in another PR. I wonder if we can disable some of these models in the interim and add to the README that they aren't yet supported... @jtcohen6 any idea how to do this? perhaps just disable the models?

2020-12-22 22:43 UTC, merged

2020-12-22 22:56 UTC, alittlesliceoftom commented
Agreed, excellent progress, thanks for the contribution and the merge!


On Tue, 22 Dec 2020 at 22:43, Anders <notifications@github.com> wrote:

> Merged #11 <https://github.com/dbt-msft/tsql-utils/pull/11> into
> port_macros.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dbt-msft/tsql-utils/pull/11#event-4142012658>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACVRBJNHOR7UBIANNNZ4CD3SWEOKBANCNFSM4U7H3NYQ>
> .
>

2020-12-22 23:06 UTC, jtcohen6 commented
yup, just disable the models! exactly as you did in bc6099f (nice anchor)